#! /usr/bin/env python3

# Export Gettext builtin plurals

import re
from urllib.request import urlopen

URL = 'http://git.savannah.gnu.org/cgit/gettext.git/plain/gettext-tools/src/plural-table.c'
MATCH = re.compile(r'\s*{\s*"([^"]*)",\s*"([^"]*)",\s*"([^"]*)"\s*},\s*')

with urlopen(URL) as handle:
    content = handle.read().decode('utf-8')

output = []
state = 0
for line in content.splitlines():
    if 'plural_table' in line:
        state = 1
        continue
    if state == 1:
        matches = MATCH.match(line)
        if matches:
            output.append('{};{};{};{}\n'.format(
                matches[1],
                matches[2],
                int(matches[3].split(';', 1)[0].split('=')[1]),
                matches[3].split(';', 1)[1].split('=', 1)[1].rstrip(';'),
            ))

with open('gettext.csv', 'w') as handle:
    handle.writelines(sorted(output))
