#! /usr/bin/env python3
#
# Copyright © 2018 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#

import json
import pprint

BASE = "modules/cldr-core/supplemental/plurals.json"

result = {}

with open(BASE, "r") as handle:
    data = json.load(handle)

for locale, rules in data["supplemental"]["plurals-type-cardinal"].items():
    result[locale] = [
        name.replace("pluralRule-count-", "")
        for name, rule in rules.items()
        if "@integer" in rule
    ]

print(pprint.pformat(result))
