#! /usr/bin/env python3
#
# Copyright © 2018 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#

OLDCODES = set(('in', 'iw', 'jw', 'ji', 'no', 'es_ES', 'mo', 'sh', 'es_419', 'ar_001'))

import csv
import gettext

def fmt_plural(data):
    return 'nplurals={}; plural={};'.format(data[2], data[3]).replace('|', '\\|')

def compare_definition(first, second, meta=True):
    if meta and (first[0] != second[0] or first[1] != second[1] or first[2] != second[2]):
        return False
    # Convert formulas to functions
    ours = gettext.c2py(first[3])
    theirs = gettext.c2py(second[3])

    # Compare equation results
    # It would be better to compare formulas,
    # but this was easier to implement and the performance
    # is still okay.
    for i in range(-10, 200):
        if ours(i) != theirs(i):
            return False

    return True


# Read the definitions
def parse_csv(name):
    result = {}
    with open(name, 'r') as csvfile:
        reader = csv.reader(csvfile, delimiter=';')
        for data in reader:
            if data[0] in result:
                print('Duplicate {} in {}!'.format(data[0], name))
                continue
            result[data[0]] = data
    return result

LANGUAGES = parse_csv('languages.csv')
CLDR = parse_csv('cldr.csv')
GETTEXT = parse_csv('gettext.csv')

# Iterate over common languages
for code in sorted(set(CLDR) & set(LANGUAGES)):
    if not compare_definition(CLDR[code], LANGUAGES[code]):
        print('Definition for {} differs:'.format(code))
        print('Languages:', LANGUAGES[code])
        print('CLDR:', CLDR[code])
        print()

# Iterate over common languages
for code in sorted(set(GETTEXT) & set(LANGUAGES)):
    if not compare_definition(GETTEXT[code], LANGUAGES[code]):
        print('Definition for {} differs:'.format(code))
        print('Languages:', LANGUAGES[code])
        print('Gettext:', GETTEXT[code])
        print()

# List missing ones
for code in sorted(set(CLDR) - set(LANGUAGES) - OLDCODES):
    print('Definition for {} missing in languages:'.format(code))
    print('CLDR:', CLDR[code])
    print()

# List missing ones
for code in sorted(set(GETTEXT) - set(LANGUAGES) - OLDCODES):
    print('Definition for {} missing in languages:'.format(code))
    print('Gettext:', GETTEXT[code])
    print()

with open('PLURALS_DIFF.md', 'w') as handle:
    handle.write('''
## Difference in plurals

This table lists differences in plurals between various sources.

* The Plurals column lists data in languages.csv used in Weblate
* CLDR are differences in plurals contained in the CLDR
* Gettext are differences in plurals contained in the Gettext sources

Code | Name | Plurals | CLDR plurals | Gettext plurals
---- | ---- | --------| ------------ | ---------------
''')
    for code in sorted(set(LANGUAGES)):
        handle.write(code.replace('_', '\\_'))
        handle.write(' | ')
        handle.write(LANGUAGES[code][1])
        handle.write(' | ')
        handle.write(fmt_plural(LANGUAGES[code]))
        handle.write(' | ')
        if code in CLDR and not compare_definition(LANGUAGES[code], CLDR[code], False):
            handle.write(fmt_plural(CLDR[code]))
        handle.write(' | ')
        if code in GETTEXT and not compare_definition(LANGUAGES[code], GETTEXT[code], False):
            handle.write(fmt_plural(GETTEXT[code]))
        handle.write('\n')
