SPDX-PackageDownloadLocation = "https://weblate.org/"
SPDX-PackageName = "weblate-language-data"
SPDX-PackageSupplier = "Michal Čihař <michal@weblate.org>"
version = 1

[[annotations]]
path = "weblate_language_data/locale/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "languages-po/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "**.csv"
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["PLURALS_DIFF.md", "README.rst"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  ".gitignore",
  ".gitmodules",
  ".weblate",
  ".well-known/*",
  "MANIFEST.in",
  "pyproject.toml",
  "requirements**.txt",
  "REUSE.toml",
  "setup.cfg"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Michal Čihař <michal@weblate.org>"
SPDX-License-Identifier = "MIT"
