#! /usr/bin/env python3

import csv
import json

IGNORE = {"nb", "no", "zh"}


def parse_csv(name):
    result = {}
    with open(name, "r") as csvfile:
        reader = csv.reader(csvfile, delimiter=";")
        for data in reader:
            if data[0] == "#":
                continue
            if data[0] in result:
                raise Exception("Duplicate {} in {}!".format(data[0], name))
            result[data[0]] = data
    return result


languages = parse_csv("languages.csv")
aliases = parse_csv("aliases.csv")

with open("/usr/share/iso-codes/json/iso_639-2.json", "r") as handle:
    for item in json.load(handle)["639-2"]:
        if "alpha_2" not in item:
            continue
        if item["alpha_2"] not in IGNORE and item["alpha_2"] not in languages:
            print(item)
        if item["alpha_3"] not in aliases:
            print(item)
