#! /usr/bin/env python3

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: MIT

import json
import sys
from urllib.request import urlopen

names = {}

# See https://github.com/WeblateOrg/language-data/issues/103
PLURALDATA = "https://jibecfed.fedorapeople.org/partage/languages-data/{}.json"

with open("modules/iso-codes/data/iso_639-2.json") as handle:
    for item in json.load(handle)["639-2"]:
        for value in ("alpha_2", "alpha_3"):
            if value in item:
                names[item[value]] = item.get("inverted_name", item["name"])

with open("modules/iso-codes/data/iso_639-3.json") as handle:
    for item in json.load(handle)["639-3"]:
        for value in ("alpha_2", "alpha_3"):
            if value in item:
                names[item[value]] = item.get("inverted_name", item["name"])

with open("languages.csv") as handle:
    lines = handle.readlines()
    header = lines[:1]
    lines = lines[1:]

for code in sys.argv[1:]:
    plurals = 2
    formula = "n != 1"
    try:
        with urlopen(PLURALDATA.format(code)) as handle:
            data = json.load(handle)
            for plural in data[code]["Plural-Forms"]:
                if not plural or "INTEGER" in plural:
                    continue
                parts = plural.split(";", 1)
                plurals = int(parts[0].split("=")[1].strip())
                if "plural" in parts[1]:
                    formula = parts[1].split("=", 1)[1].strip().rstrip(";")
                else:
                    formula = parts[1]
                if formula.replace(" ", "") == "(n!=1)":
                    formula = "n != 1"
                if formula == "n != 1":
                    continue
                break
    except (OSError, KeyError):
        sys.stderr.write(f"Failed to load data for {code}, using defaults\n")
    lines.append(
        "{},{},{},{}\n".format(
            code,
            names[code].split(";")[-1].strip(),
            plurals,
            formula,
        ),
    )

with open("languages.csv", "w") as handle:
    handle.writelines(header)
    handle.writelines(sorted(lines))
