#! /usr/bin/env python3

# Export Gettext builtin plurals

import sys

sys.path.insert(0, "./modules/translate/")

from translate.lang.data import languages

output = []
state = 0
for code, data in languages.items():
    output.append("{};{};{};{}\n".format(code, data[0].split(";")[0], data[1], data[2]))

with open("translate.csv", "w") as handle:
    handle.writelines(sorted(output))
