#! /usr/bin/env python3

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: MIT

import json
from collections import defaultdict

MAPPING = {
    "zh": "zh_Hans",
}

with open(
    "modules/cldr-json/cldr-json/cldr-core/supplemental/territoryInfo.json"
) as handle:
    languages = defaultdict(int)
    for code, territory in json.load(handle)["supplemental"]["territoryInfo"].items():
        population = int(territory["_population"])
        if "languagePopulation" not in territory:
            print(f"Skipping {code}: {territory}")
            continue
        for language_cldr, data in territory["languagePopulation"].items():
            language = MAPPING.get(language_cldr, language_cldr)
            languages[language] += population * float(data["_populationPercent"])
            languages[f"{language}_{code}"] += population * float(
                data["_populationPercent"]
            )

with open("population.csv", "w") as handle:
    handle.write("code,population\n")
    for code in sorted(languages):
        handle.write(f"{code},{int(languages[code])}\n")
