#! /usr/bin/env python3
#
# Copyright © 2018 - 2020 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

import csv
import json
import subprocess

IGNORE = {"nb", "no", "zh"}


def parse_csv(name):
    result = {}
    with open(name, "r") as csvfile:
        reader = csv.reader(csvfile, delimiter=";")
        for data in reader:
            if data[0] == "#":
                continue
            if data[0] in result:
                raise Exception("Duplicate {} in {}!".format(data[0], name))
            result[data[0]] = data
    return result


languages = parse_csv("languages.csv")
aliases = parse_csv("aliases.csv")

with open("modules/iso-codes/data/iso_639-2.json", "r") as handle:
    for item in json.load(handle)["639-2"]:
        if "alpha_2" not in item:
            continue
        if item["alpha_2"] not in IGNORE and item["alpha_2"] not in languages:
            subprocess.run(["./scripts/add-iso", item["alpha_2"]])
