#! /usr/bin/env python3
#
# Copyright © Michal Čihař <michal@weblate.org>
#
# This file is part of Weblate <https://weblate.org/>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

"""Export l10n guide plurals."""

import re

MATCH = re.compile(r"\s*([^,]+),\s*([^,#]+)( \[#f[0-9]*\]_)?,\s*(nplurals.*)\s*")

with open("modules/l10n-guide/docs/l10n/pluralforms.rst") as handle:
    content = handle.read()

output = []
state = 0
for line in content.splitlines():
    if "csv-table" in line:
        state = 1
        continue
    if state == 1:
        matches = MATCH.match(line)
        if matches:
            plural_parts = matches[4].split(";")
            output.append(
                "{},{},{},{}\n".format(
                    matches[1],
                    matches[2],
                    int(plural_parts[0].split("=")[1]),
                    plural_parts[1].split("=", 1)[1].rstrip(";"),
                )
            )

with open("l10n-guide.csv", "w") as handle:
    handle.write("code,name,nplurals,formula\n")
    handle.writelines(sorted(output))
