#! /usr/bin/env python3
#
# Copyright © 2018 - 2021 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

import csv
import json

names = {}


def parse_csv(name):
    result = {}
    with open(name) as csvfile:
        reader = csv.reader(csvfile, delimiter=";")
        for data in reader:
            if data[0] == "#":
                continue
            if data[0] in result:
                raise Exception("Duplicate {} in {}!".format(data[0], name))
            result[data[0]] = data
    return result


def add_name(item):
    if "alpha_2" not in item:
        return
    if "alpha_3" in item:
        names[item["alpha_3"]] = item["alpha_2"]
    if "bibliographic" in item:
        names[item["bibliographic"]] = item["alpha_2"]


with open("modules/iso-codes/data/iso_639-2.json") as handle:
    for item in json.load(handle)["639-2"]:
        add_name(item)

with open("modules/iso-codes/data/iso_639-3.json") as handle:
    for item in json.load(handle)["639-3"]:
        add_name(item)

aliases = parse_csv("aliases.csv")

lines = []
for name, alias in sorted(names.items()):
    if name not in aliases:
        lines.append(f"{name};{alias}\n")

if lines:
    with open("aliases.csv", "a") as handle:
        handle.writelines(sorted(lines))
