#! /usr/bin/env python3
#
# Copyright © 2012–2023 Michal Čihař <michal@cihar.com>
#
# This file is part of Weblate <https://weblate.org/>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

import csv
import gettext

IGNOREDCODES = {
    # Obsolete language codes
    "in",
    "iw",
    "jw",
    "ji",
    "no",
    "es_ES",
    "mo",
    "sh",
    "zh_TW",
    "zh_HK",
    "zh_CN",
    # Ignore some variants
    "es_419",
    "ar_001",
}


def fmt_plural(data):
    return f"nplurals={data[2]}; plural={data[3]};".replace("|", "\\|")


def compare_definition(first, second, meta=True):
    if meta and (
        first[0] != second[0] or first[1] != second[1] or first[2] != second[2]
    ):
        return False
    # Convert formulas to functions
    ours = gettext.c2py(first[3])
    theirs = gettext.c2py(second[3])

    # Compare equation results
    # It would be better to compare formulas,
    # but this was easier to implement and the performance
    # is still okay.
    for i in range(-10, 200):
        if ours(i) != theirs(i):
            return False

    return True


# Read the definitions
def parse_csv(name):
    result = {}
    with open(name) as csvfile:
        reader = csv.reader(csvfile, delimiter=",")
        next(reader)
        for data in reader:
            if data[0] in result:
                print(f"Duplicate {data[0]} in {name}!")
                continue
            result[data[0]] = data
    return result


def show_diff(name, data):
    for code in sorted(set(data) & set(LANGUAGES)):
        if not compare_definition(data[code], LANGUAGES[code]):
            print(f"Definition for {code} differs:")
            print("Languages:", LANGUAGES[code])
            print(name, ":", data[code])
            print()


def show_missing(name, data):
    for code in sorted(set(data) - set(LANGUAGES) - IGNOREDCODES):
        print(f"Definition for {code} missing in languages:")
        print(name, ":", data[code])
        print()


LANGUAGES = parse_csv("languages.csv")
CLDR = parse_csv("cldr.csv")
GETTEXT = parse_csv("gettext.csv")
L10N = parse_csv("l10n-guide.csv")
TRANSLATE = parse_csv("translate.csv")

# List differences
show_diff("CLDR", CLDR)
show_diff("Gettext", GETTEXT)
show_diff("L10n guide", L10N)
show_diff("Translate", TRANSLATE)

# List missing ones
show_missing("CLDR", CLDR)
show_missing("Gettext", GETTEXT)
show_missing("L10n guide", L10N)
show_missing("Translate", TRANSLATE)

with open("PLURALS_DIFF.md", "w") as handle:
    handle.write(
        """
## Difference in plurals

This table lists differences in plurals between various sources.
The Plurals column lists data in languages.csv which is used in Weblate

Code | Name | Plurals | CLDR plurals | Gettext plurals | L10n guide | Translate toolkit
---- | ---- | --------| ------------ | --------------- | ---------- | -----------------
"""
    )
    for code in sorted(set(LANGUAGES)):
        handle.write(code.replace("_", "\\_"))
        handle.write(" | ")
        handle.write(LANGUAGES[code][1])
        handle.write(" | ")
        handle.write(fmt_plural(LANGUAGES[code]))
        handle.write(" | ")
        if code in CLDR:
            if not compare_definition(LANGUAGES[code], CLDR[code], False):
                handle.write(fmt_plural(CLDR[code]))
            else:
                handle.write("✔")
        handle.write(" | ")
        if code in GETTEXT:
            if not compare_definition(LANGUAGES[code], GETTEXT[code], False):
                handle.write(fmt_plural(GETTEXT[code]))
            else:
                handle.write("✔")
        handle.write(" | ")
        if code in L10N:
            if not compare_definition(LANGUAGES[code], L10N[code], False):
                handle.write(fmt_plural(L10N[code]))
            else:
                handle.write("✔")
        handle.write(" | ")
        if code in TRANSLATE:
            if not compare_definition(LANGUAGES[code], TRANSLATE[code], False):
                handle.write(fmt_plural(TRANSLATE[code]))
            else:
                handle.write("✔")
        handle.write("\n")
